### ISSUE TITLE
lst_l" is not defined

### ISSUE THREAD

**Issue by xiaochen778** [Wei9711/NegGCNs#1]
in the definition of func GetComuFeatureMatrix, the variable lst_l" is not defined:
def GetComuFeatureMatrix(label_community,featuresNum,x):
  temp = 0
  n = 0
  ComuFeatureM = torch.zeros(len(label_community), featuresNum)
  for c in **_lst_l:_**
    for ele in c:
      temp= temp + x[ele]
    ComuFeatureM[n] = temp / len(c)
    n = n+1
  return ComuFeatureM

**Comment by Wei9711** [comment]
Thank you for pointing out this bug. I have revised the code. "**lst_l**" should be "**LabelComu**". 

Before the revision, the "GetComuFeatureMatrix(self,x)" function is also written in the class of SDGCN, so it doesn't affect the computing of the whole algorithm.
